export const FREE_TIER_REQUESTS_LIMIT = 20
export const FREE_TIER_USAGE_LIMIT = 2.00

export const PRO_TIER_REQUESTS_LIMIT = 500
export const PRO_TIER_USAGE_LIMIT = 10.00

export const OVERAGE_PRICE = 0.05