import { NextRequest, NextResponse } from 'next/server'
import { createSupabaseAppServerClient } from '@/lib/utils/supabase/server'
import { serverRequestService } from '@/lib/services/requestService'

const PYTHON_BACKEND_URL = process.env.PYTHON_BACKEND_URL || 'https://juniper-python-backend.onrender.com'

interface ChatMessage {
  role: 'user' | 'assistant'
  content: string
  timestamp: number
  imageUrl?: string
}

interface ChatRequest {
  message: string
  imageUrl?: string
  history: ChatMessage[]
  request_id?: string
  integration_in_progress?: boolean
  service_name?: string
  user_id?: string
  conversation_id?: string
}

export async function POST(request: NextRequest) {
  let requestId: string | undefined;
 
  try {
    // Get authenticated user (recommended for server-side validation)
    const supabase = await createSupabaseAppServerClient()
    
    const { data: { user }, error: authError } = await supabase.auth.getUser()
   
    
    if (authError || !user) {
      console.log('Authentication failed - returning 401')
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    // Get session to extract access token for external API
    const { data: { session }, error: sessionError } = await supabase.auth.getSession()
    console.log('Session check result:', { 
      hasSession: !!session,
      hasAccessToken: !!session?.access_token,
      accessTokenLength: session?.access_token?.length,
      sessionError: sessionError?.message 
    })
    
    if (sessionError || !session?.access_token) {
      console.log('Session validation failed - returning 401')
      return NextResponse.json(
        { error: 'No valid session token' },
        { status: 401 }
      )
    }

    // Parse request body
    const body: ChatRequest = await request.json()
    const { message, imageUrl, history, request_id, integration_in_progress, service_name, conversation_id } = body

    if ((!message || typeof message !== 'string') && !imageUrl) {
      return NextResponse.json(
        { error: 'Message or image is required' },
        { status: 400 }
      )
    }

    // Get user profile for settings
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('general_instructions, base_language_model, timezone')
      .eq('id', user.id)
      .single()

    // Use provided request ID or generate one as fallback
    requestId = request_id || `web-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
    console.log('Using request ID:', requestId, request_id ? '(provided by frontend)' : '(generated by backend)')

    // Create request record in database
    try {
      await serverRequestService.createRequest(user.id, {
        request_id: requestId,
        request_type: 'chat',
        status: 'pending',
        metadata: {
          message: message?.trim() || '',
          imageUrl: imageUrl || null,
          integration_in_progress: integration_in_progress || false,
          service_name: service_name || null,
          timestamp: Date.now()
        },
        conversation_id: conversation_id,
        network_success: true
      })
    } catch (requestError) {
      console.error('Failed to create request record:', requestError)
      return NextResponse.json(
        { error: 'Failed to create request record' },
        { status: 500 }
      )
    }

    // Update request status to processing
    try {
      await serverRequestService.updateRequestStatus(requestId, 'processing')
    } catch (updateError) {
      console.error('Failed to update request status to processing:', updateError)
    }

    // Prepare request for Python backend (matching backend ChatRequest model)
    const chatRequest = {
      message: message?.trim() || '',
      timestamp: Date.now(),
      history: history.map(msg => ({
        role: msg.role,
        content: msg.content,
        timestamp: msg.timestamp,
        type: msg.imageUrl ? 'image' : 'text',
        image_url: msg.imageUrl || null
      })),
      preferences: {
        general_instructions: profile?.general_instructions || '',
        base_language_model: profile?.base_language_model || 'gpt-4',
        timezone: profile?.timezone || 'UTC'
      },
      request_id: requestId,
      integration_in_progress: integration_in_progress || false,
      image_url: imageUrl || null,
      service_name: service_name || null
    }

    // Call Python backend using FormData format (matching React Native)
    const formData = new FormData()
    formData.append('json_data', JSON.stringify(chatRequest))
    

    const response = await fetch(`${PYTHON_BACKEND_URL}/api/chat`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${session.access_token}`,
      },
      body: formData,
    })


    if (!response.ok) {
      const errorText = await response.text()
      console.error('Python backend error details:', {
        status: response.status,
        statusText: response.statusText,
        errorText: errorText
      })
      throw new Error(`Backend error: ${response.status}`)
    }

    const data = await response.json()
    console.log('Python backend success response:', {
      hasResponse: !!data.response,
      responseLength: data.response?.length,
      timestamp: data.timestamp,
      settingsUpdated: data.settings_updated,
      integrationInProgress: data.integration_in_progress
    })

    // Update usage statistics if needed
    if (data.usage_updated) {
      // The Python backend handles usage updates, but we could add additional logic here if needed
    }

    // Update request status to completed
    try {
      await serverRequestService.updateRequestStatus(requestId, 'completed', {
        response: data.response,
        backend_timestamp: data.timestamp
      })
    } catch (updateError) {
      console.error('Failed to update request status to completed:', updateError)
    }

    console.log('=== CHAT API REQUEST SUCCESS ===')
    return NextResponse.json({
      response: data.response,
      timestamp: data.timestamp,
      settings_updated: data.settings_updated || false,
      integration_in_progress: data.integration_in_progress || false,
      request_id: requestId,
    })

  } catch (error) {
    console.error('=== CHAT API REQUEST FAILED ===')
    console.error('Chat API error:', error)
    console.error('Error stack:', error instanceof Error ? error.stack : 'No stack trace')

    // Check if this is a network error
    const isNetworkError = error instanceof Error && (
      error.message.includes('fetch failed') ||
      error.message.includes('ECONNREFUSED') ||
      error.message.includes('ENOTFOUND') ||
      error.message.includes('ETIMEDOUT') ||
      error.message.includes('Network Error') ||
      error.name === 'TypeError' && error.message.includes('fetch')
    )

    // Update request status to failed if we have a requestId in scope
    if (typeof requestId !== 'undefined') {
      try {
        await serverRequestService.updateRequestStatus(requestId, 'failed', {
          error: error instanceof Error ? error.message : 'Unknown error',
          error_timestamp: Date.now()
        })

        // Set network_success to false only for actual network errors
        if (isNetworkError) {
          await serverRequestService.updateNetworkSuccess(requestId, false)
          console.error('Network error detected - set network_success to false')
        }
      } catch (updateError) {
        console.error('Failed to update request status to failed:', updateError)
      }
    }

    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}